ifeq (X$(TREEHOME), X)
TREEHOME=$(HOME)/StarAndBH/tree16
endif
##### Application-specific stuff goes here

src=main_sph.c grav_nv.c cofm_sph.c print.c \
        rdtest.c sph.c integrate.c gravity.c physics_sph.c boost.c grav_rad.c \
        shrink.c # roche.c
programname=grsph
treedir=$(TREEHOME)

appexcludes:=-name data

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.

$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf): $(treedir)/include/Assert.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/error.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/SDF.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/protos.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/macr.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/malloc.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/SDFwrite.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/SDFread.h
$(objdir)/main_sph$(objsuf): physics_sph.h $(treedir)/include/tree.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/timers.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/key.h
$(objdir)/main_sph$(objsuf):
$(objdir)/main_sph$(objsuf): $(treedir)/include/stk.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/chn.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/vop.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/singlio.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/gc.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/files.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/getparam.h
$(objdir)/main_sph$(objsuf): $(treedir)/include/verify.h integrate.h
$(objdir)/grav_nv$(objsuf): physics_sph.h $(treedir)/include/tree.h
$(objdir)/grav_nv$(objsuf):
$(objdir)/grav_nv$(objsuf): $(treedir)/include/timers.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/key.h
$(objdir)/grav_nv$(objsuf):
$(objdir)/grav_nv$(objsuf): $(treedir)/include/stk.h
$(objdir)/grav_nv$(objsuf):
$(objdir)/grav_nv$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/error.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/chn.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/vop.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/tensop.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/grav_nv$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/cofm_sph$(objsuf):
$(objdir)/cofm_sph$(objsuf):
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/tree.h
$(objdir)/cofm_sph$(objsuf):
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/timers.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/key.h
$(objdir)/cofm_sph$(objsuf):
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/stk.h
$(objdir)/cofm_sph$(objsuf):
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/error.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/chn.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/pqsort.h physics_sph.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/vop.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/Assert.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/cofm_sph$(objsuf): $(treedir)/include/protos.h
$(objdir)/print$(objsuf): physics_sph.h
$(objdir)/print$(objsuf): $(treedir)/include/tree.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/timers.h
$(objdir)/print$(objsuf): $(treedir)/include/key.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/stk.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/print$(objsuf): $(treedir)/include/error.h
$(objdir)/print$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/print$(objsuf): $(treedir)/include/chn.h
$(objdir)/print$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/print$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/print$(objsuf): $(treedir)/include/protos.h
$(objdir)/print$(objsuf): $(treedir)/include/vop.h
$(objdir)/rdtest$(objsuf):
$(objdir)/rdtest$(objsuf):
$(objdir)/rdtest$(objsuf): $(treedir)/include/randoms.h physics_sph.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/tree.h
$(objdir)/rdtest$(objsuf):
$(objdir)/rdtest$(objsuf): $(treedir)/include/timers.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/key.h
$(objdir)/rdtest$(objsuf):
$(objdir)/rdtest$(objsuf): $(treedir)/include/stk.h
$(objdir)/rdtest$(objsuf):
$(objdir)/rdtest$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/error.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/chn.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/vop.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/rdtest$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/sph$(objsuf): physics_sph.h $(treedir)/include/tree.h
$(objdir)/sph$(objsuf):
$(objdir)/sph$(objsuf): $(treedir)/include/timers.h
$(objdir)/sph$(objsuf): $(treedir)/include/key.h
$(objdir)/sph$(objsuf): $(treedir)/include/stk.h
$(objdir)/sph$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/sph$(objsuf): $(treedir)/include/error.h
$(objdir)/sph$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/sph$(objsuf): $(treedir)/include/chn.h
$(objdir)/sph$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/sph$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/sph$(objsuf): $(treedir)/include/vop.h
$(objdir)/sph$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/integrate$(objsuf): physics_sph.h $(treedir)/include/tree.h
$(objdir)/integrate$(objsuf):
$(objdir)/integrate$(objsuf): $(treedir)/include/timers.h
$(objdir)/integrate$(objsuf): $(treedir)/include/key.h
$(objdir)/integrate$(objsuf):
$(objdir)/integrate$(objsuf): $(treedir)/include/stk.h
$(objdir)/integrate$(objsuf):
$(objdir)/integrate$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/integrate$(objsuf): $(treedir)/include/error.h
$(objdir)/integrate$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/integrate$(objsuf): $(treedir)/include/chn.h
$(objdir)/integrate$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/integrate$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/integrate$(objsuf): integrate.h $(treedir)/include/vop.h
$(objdir)/gravity$(objsuf): physics_sph.h $(treedir)/include/tree.h
$(objdir)/gravity$(objsuf):
$(objdir)/gravity$(objsuf): $(treedir)/include/timers.h
$(objdir)/gravity$(objsuf): $(treedir)/include/key.h
$(objdir)/gravity$(objsuf):
$(objdir)/gravity$(objsuf): $(treedir)/include/stk.h
$(objdir)/gravity$(objsuf):
$(objdir)/gravity$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/gravity$(objsuf): $(treedir)/include/error.h
$(objdir)/gravity$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/gravity$(objsuf): $(treedir)/include/chn.h
$(objdir)/gravity$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/gravity$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/gravity$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/gravity$(objsuf): $(treedir)/include/vop.h
$(objdir)/physics_sph$(objsuf): physics_sph.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/tree.h
$(objdir)/physics_sph$(objsuf):
$(objdir)/physics_sph$(objsuf): $(treedir)/include/timers.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/key.h
$(objdir)/physics_sph$(objsuf):
$(objdir)/physics_sph$(objsuf): $(treedir)/include/stk.h
$(objdir)/physics_sph$(objsuf):
$(objdir)/physics_sph$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/error.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/chn.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/physics_generic.c
$(objdir)/physics_sph$(objsuf):
$(objdir)/physics_sph$(objsuf):
$(objdir)/physics_sph$(objsuf): $(treedir)/include/protos.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/vop.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/Assert.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/verify.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/files.h
$(objdir)/physics_sph$(objsuf): $(treedir)/include/gc.h
$(objdir)/boost$(objsuf):
$(objdir)/boost$(objsuf): physics_sph.h
$(objdir)/boost$(objsuf): $(treedir)/include/tree.h
$(objdir)/boost$(objsuf):
$(objdir)/boost$(objsuf): $(treedir)/include/timers.h
$(objdir)/boost$(objsuf): $(treedir)/include/key.h
$(objdir)/boost$(objsuf):
$(objdir)/boost$(objsuf): $(treedir)/include/stk.h
$(objdir)/boost$(objsuf):
$(objdir)/boost$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/boost$(objsuf): $(treedir)/include/error.h
$(objdir)/boost$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/boost$(objsuf): $(treedir)/include/chn.h
$(objdir)/boost$(objsuf): $(treedir)/include/pqsort.h
$(objdir)/boost$(objsuf): $(treedir)/include/physics_generic.h
$(objdir)/boost$(objsuf): $(treedir)/include/vop.h
$(objdir)/roche$(objsuf):
$(objdir)/roche$(objsuf): physics_sph.h
