char datafile[]="NS.nobh.2000";
char outfile[]="NS.fall.bhm10.r10.J0";
char statsfile[]="NS.fall.bhm10.r10.J0.dat";
int do_kerr = 1;
int do_setup = 1;		/* Set to zero unless first step. */
float hole_mass = 1.;		/* Set to zero to remove the hole's gravity. */
float kerr_ang_mom =  0.;
float r_horizon = 2.0;
float xx0 =  10.;
float yy0 =  0.;
float zz0 =  0.;
float vx0 =  -0.2;
float vy0 =  0.;
float vz0 =  0.;
float bhmass = 10.0;		/* Black Hole Mass in solar units */
float Gamma = 1.6667;
float dacc_factor = 1.e-2;	/* tolerance for time-steps */
int absolute_tol = 1;
float epsilon=0.01;
float errtol=1e-4;
float dt=0.005;
float visc_alpha=0.;
float visc_beta=0.;
int nsteps=2000;
int output_freq=200;
int timer_freq = 40;
int load_balance = 1;
int save_first = 1;
int adaptive_dt = 1;          /* set to zero for uniform time-step   */
char Msg_turn_on[]="nomsgs";
int do_gravity = 1;           /* set to zero to turn OFF self-gravity */
int no_hydro = 0;             /* set to zero to turn ON the hydro     */
/* Added for relaxation - Don */
float dt_upper_limit=0.03;
float max_h = 10000.;
float min_h = 0;
int nbrcut_max = 10000;
int nbrcut_min = 0;
## SDF-EOH

