ifeq (X$(TREEHOME), X)
TREEHOME=../../
endif
##### Application-specific stuff goes here
treedir=$(TREEHOME)

src=massr.c
programname=massr

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.
