src=init.c prft.c holtz_cdm.c ebw_cdm.c realft.c four1.c ran1.c ft.c fourn.c \
	powlaw.c dofZ.c qromo.c
programname=cdm
treedir=../../../tree16

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.

$(objdir)/init$(objsuf):
$(objdir)/init$(objsuf):
$(objdir)/init$(objsuf):
$(objdir)/init$(objsuf): $(treedir)/include/protos.h
$(objdir)/init$(objsuf): $(treedir)/include/timers.h
$(objdir)/init$(objsuf): $(treedir)/include/singlio.h
$(objdir)/init$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/init$(objsuf): $(treedir)/include/mpmy_io.h
$(objdir)/init$(objsuf): $(treedir)/include/randoms.h
$(objdir)/init$(objsuf): $(treedir)/include/Assert.h
$(objdir)/init$(objsuf): $(treedir)/include/error.h
$(objdir)/init$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/init$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/init$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/SDF.h
$(objdir)/init$(objsuf): $(treedir)/include/getparam.h
$(objdir)/prft$(objsuf):
$(objdir)/prft$(objsuf): $(treedir)/include/bigmalloc.h
$(objdir)/prft$(objsuf): $(treedir)/include/error.h
$(objdir)/prft$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/prft$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/prft$(objsuf): $(treedir)/include/timers.h
$(objdir)/prft$(objsuf): $(treedir)/include/protos.h
$(objdir)/prft$(objsuf): $(treedir)/include/singlio.h
$(objdir)/prft$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/prft$(objsuf): $(treedir)/include/Assert.h
$(objdir)/prft$(objsuf): $(treedir)/include/randoms.h complex.h
$(objdir)/holtz_cdm$(objsuf):
$(objdir)/holtz_cdm$(objsuf):
$(objdir)/holtz_cdm$(objsuf): $(treedir)/include/singlio.h
$(objdir)/holtz_cdm$(objsuf): $(treedir)/include/randoms.h
$(objdir)/holtz_cdm$(objsuf): $(treedir)/include/error.h
$(objdir)/holtz_cdm$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/ebw_cdm$(objsuf):
$(objdir)/ebw_cdm$(objsuf): $(treedir)/include/singlio.h
$(objdir)/ebw_cdm$(objsuf): $(treedir)/include/randoms.h
$(objdir)/ebw_cdm$(objsuf): $(treedir)/include/error.h
$(objdir)/ebw_cdm$(objsuf): $(treedir)/include/gccextensions.h
$(objdir)/realft$(objsuf):
$(objdir)/realft$(objsuf):
$(objdir)/four1$(objsuf):
$(objdir)/four1$(objsuf):
