src=ft3.c four1.c nrutil.c ran1.c
programname=ft3
treedir=../../../tree16

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.
