treedir_sed=\.\.
##### Application-specific stuff goes here

src=main_panel.c cofm_panel.c mac.c physics_panel.c \
  integrate_panel.c mono_panel.c quads_panel.c prepare_panel.c print.c

programname=panel
treedir=..

appexcludes:=-name data

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

$(objdir)/grav$(objsuf) : grav.c
	$(CC) $(CFLAGS) $(AGGRESSIVE_OPT) -c grav.c
	mv grav$(objsuf) $(objdir)

# DO NOT DELETE THIS LINE -- make depend depends on it.

$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf): $(treedir)/include/fastflpt.h physics_panel.h $(treedir)/include/tree.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/SDF.h
$(objdir)/main_panel$(objsuf):
$(objdir)/main_panel$(objsuf): $(treedir)/include/SDFwrite.h $(treedir)/include/protos.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/vop.h $(treedir)/include/Msgs.h $(treedir)/include/files.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/getparam.h $(treedir)/include/mpmy.h
$(objdir)/main_panel$(objsuf): $(treedir)/include/malloc.h
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf): physics_panel.h $(treedir)/include/tree.h
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/cofm_panel$(objsuf):
$(objdir)/cofm_panel$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/mac$(objsuf): physics_panel.h $(treedir)/include/tree.h
$(objdir)/mac$(objsuf):
$(objdir)/mac$(objsuf):
$(objdir)/mac$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/mac$(objsuf):
$(objdir)/mac$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h
$(objdir)/mac$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/mac$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/mac$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/physics_panel$(objsuf): physics_panel.h $(treedir)/include/tree.h
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h
$(objdir)/physics_panel$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/physics_panel$(objsuf): $(treedir)/include/chn.h $(treedir)/include/Assert.h
$(objdir)/physics_panel$(objsuf): $(treedir)/include/pqsort.h $(treedir)/include/physics_generic.h
$(objdir)/physics_panel$(objsuf): $(treedir)/include/physics_generic.c
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf): $(treedir)/include/protos.h
$(objdir)/physics_panel$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/vop.h $(treedir)/include/Msgs.h
$(objdir)/physics_panel$(objsuf):
$(objdir)/physics_panel$(objsuf): $(treedir)/include/verify.h $(treedir)/include/files.h
$(objdir)/physics_panel$(objsuf): $(treedir)/include/gc.h
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf): physics_panel.h
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/tree.h
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf):
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/stk.h
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/integrate_panel$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf): $(treedir)/include/protos.h
$(objdir)/mono_panel$(objsuf): physics_panel.h $(treedir)/include/tree.h
$(objdir)/mono_panel$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/mono_panel$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/mono_panel$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/mono_panel$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/Msgs.h
$(objdir)/mono_panel$(objsuf):
$(objdir)/mono_panel$(objsuf): $(treedir)/include/fastflpt.h $(treedir)/include/vop.h
$(objdir)/quads_panel$(objsuf):
$(objdir)/quads_panel$(objsuf): $(treedir)/include/protos.h physics_panel.h $(treedir)/include/tree.h
$(objdir)/quads_panel$(objsuf):
$(objdir)/quads_panel$(objsuf): $(treedir)/include/timers.h
$(objdir)/quads_panel$(objsuf): $(treedir)/include/key.h
$(objdir)/quads_panel$(objsuf):
$(objdir)/quads_panel$(objsuf): $(treedir)/include/stk.h
$(objdir)/quads_panel$(objsuf): $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/quads_panel$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/quads_panel$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/quads_panel$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/quads_panel$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/quads_panel$(objsuf):
$(objdir)/quads_panel$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf): physics_panel.h
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/tree.h
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf):
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/chn.h $(treedir)/include/Assert.h
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/pqsort.h $(treedir)/include/physics_generic.h
$(objdir)/prepare_panel$(objsuf): $(treedir)/include/vop.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): physics_panel.h $(treedir)/include/tree.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/stk.h
$(objdir)/print$(objsuf): $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/print$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/print$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/print$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/protos.h
$(objdir)/print$(objsuf): $(treedir)/include/vop.h
