TREEHOME=..
treedir_sed=\.\.
##### Application-specific stuff goes here

src=	cofm.c grav.c mac.c main.c physics.c print.c

programname=nln
treedir=$(TREEHOME)

appexcludes:=-name data

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

$(objdir)/grav$(objsuf) : grav.c
	$(CC) $(CFLAGS) $(AGGRESSIVE_OPT) -c grav.c
	mv grav$(objsuf) $(objdir)

# DO NOT DELETE THIS LINE -- make depend depends on it.

$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf): $(treedir)/include/tree.h
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h
$(objdir)/cofm$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/cofm$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h physics.h
$(objdir)/cofm$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/cofm$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/cofm$(objsuf):
$(objdir)/cofm$(objsuf): $(treedir)/include/fastflpt.h $(treedir)/include/protos.h
$(objdir)/grav$(objsuf): physics.h $(treedir)/include/tree.h
$(objdir)/grav$(objsuf):
$(objdir)/grav$(objsuf):
$(objdir)/grav$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/grav$(objsuf):
$(objdir)/grav$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h
$(objdir)/grav$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/grav$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/grav$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/grav$(objsuf): $(treedir)/include/tensop.h $(treedir)/include/fastflpt.h $(treedir)/include/Msgs.h
$(objdir)/grav$(objsuf):
$(objdir)/mac$(objsuf): physics.h $(treedir)/include/tree.h
$(objdir)/mac$(objsuf):
$(objdir)/mac$(objsuf):
$(objdir)/mac$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/mac$(objsuf):
$(objdir)/mac$(objsuf): $(treedir)/include/stk.h $(treedir)/include/bigmalloc.h
$(objdir)/mac$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/mac$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/mac$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/vop.h
$(objdir)/mac$(objsuf): $(treedir)/include/fastflpt.h $(treedir)/include/Msgs.h
$(objdir)/mac$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf): $(treedir)/include/fastflpt.h
$(objdir)/main$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/main$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/SDF.h
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf): $(treedir)/include/protos.h $(treedir)/include/macr.h $(treedir)/include/malloc.h
$(objdir)/main$(objsuf): $(treedir)/include/bigmalloc.h $(treedir)/include/SDFwrite.h $(treedir)/include/SDFread.h
$(objdir)/main$(objsuf): physics.h $(treedir)/include/tree.h $(treedir)/include/timers.h
$(objdir)/main$(objsuf): $(treedir)/include/key.h
$(objdir)/main$(objsuf):
$(objdir)/main$(objsuf): $(treedir)/include/stk.h $(treedir)/include/chn.h
$(objdir)/main$(objsuf): $(treedir)/include/pqsort.h $(treedir)/include/physics_generic.h
$(objdir)/main$(objsuf): $(treedir)/include/vop.h $(treedir)/include/Msgs.h $(treedir)/include/singlio.h
$(objdir)/main$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/mpmy_io.h
$(objdir)/main$(objsuf): $(treedir)/include/mpmy_abnormal.h $(treedir)/include/gc.h $(treedir)/include/files.h
$(objdir)/main$(objsuf): $(treedir)/include/getparam.h $(treedir)/include/verify.h $(treedir)/include/randoms.h
$(objdir)/main$(objsuf): $(treedir)/include/ring.h $(treedir)/include/decomp.h $(treedir)/include/image.h
$(objdir)/main$(objsuf): $(treedir)/include/memfile.h
$(objdir)/physics$(objsuf): physics.h $(treedir)/include/tree.h
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf): $(treedir)/include/stk.h
$(objdir)/physics$(objsuf): $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/physics$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/physics$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/physics$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/physics_generic.c
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf): $(treedir)/include/protos.h
$(objdir)/physics$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/vop.h $(treedir)/include/Msgs.h
$(objdir)/physics$(objsuf):
$(objdir)/physics$(objsuf): $(treedir)/include/verify.h $(treedir)/include/files.h $(treedir)/include/gc.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): physics.h $(treedir)/include/tree.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/timers.h $(treedir)/include/key.h
$(objdir)/print$(objsuf):
$(objdir)/print$(objsuf): $(treedir)/include/stk.h
$(objdir)/print$(objsuf): $(treedir)/include/bigmalloc.h $(treedir)/include/error.h
$(objdir)/print$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h
$(objdir)/print$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/pqsort.h
$(objdir)/print$(objsuf): $(treedir)/include/physics_generic.h $(treedir)/include/protos.h
$(objdir)/print$(objsuf): $(treedir)/include/vop.h
