ifeq (X$(TREEHOME), X)
TREEHOME=../../
endif
##### Application-specific stuff goes here
treedir=$(TREEHOME)

src=rhofield.c
programname=rhofield

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.

$(objdir)/rhofield$(objsuf) : $(incdir)/empty/stdio.h
$(objdir)/rhofield$(objsuf) : $(incdir)/empty/stddef.h
$(objdir)/rhofield$(objsuf) : $(incdir)/empty/math.h
$(objdir)/rhofield$(objsuf) : $(incdir)/SDF.h
$(objdir)/rhofield$(objsuf) : $(incdir)/empty/stdarg.h
$(objdir)/rhofield$(objsuf) : $(incdir)/mpmy.h
$(objdir)/rhofield$(objsuf) : $(incdir)/timers.h
$(objdir)/rhofield$(objsuf) : $(incdir)/vop.h
$(objdir)/rhofield$(objsuf) : $(incdir)/fastflpt.h
$(objdir)/rhofield$(objsuf) : $(incdir)/singlio.h
$(objdir)/rhofield$(objsuf) : $(incdir)/SDFread.h
$(objdir)/rhofield$(objsuf) : $(incdir)/SDFwrite.h
$(objdir)/rhofield$(objsuf) : $(incdir)/error.h
$(objdir)/rhofield$(objsuf) : $(incdir)/gccextensions.h
$(objdir)/rhofield$(objsuf) : $(incdir)/ring.h
$(objdir)/rhofield$(objsuf) : $(incdir)/randoms.h
$(objdir)/rhofield$(objsuf) : $(incdir)/bigmalloc.h
$(objdir)/rhofield$(objsuf) : $(incdir)/pqsort.h
$(objdir)/rhofield$(objsuf) : $(incdir)/key.h
$(objdir)/rhofield$(objsuf) : $(incdir)/empty/limits.h
$(objdir)/rhofield$(objsuf) : $(incdir)/Assert.h
$(objdir)/rhofield$(objsuf) : $(incdir)/Msgs.h
